export const titles = {
  suite: 'Loadmill Test Suite',
  suiteConf: 'Advanced configuration of the test suite',
  suiteMeta: 'The metadata of the suite.',
  flows: 'Test flows',
  suiteDescription: 'Suite description',
  suiteParameters: 'Suite parameters',
  suiteAuth: 'Suite auth',
  suiteAuthUser: 'Auth user',
  suiteAuthPassword: 'Auth password',
  useCookies: 'Use Cookies',
  loginFlow: 'Login flow',
  request: 'Request',
  method: 'Request method',
  url: 'Request url',
  authenticationHeaders: 'Global authentication headers',
  headers: 'Request Headers',
  header: 'Request Header',
  sharedLoginFlowDescription: 'Shared Login Flow Description',
  parametersScope: 'Parameters Scope',
  flowId: 'Flow Identifier',
  flowOrder: 'Flow Order',
  runInCi: 'CI Toggle',
  flowConf: 'Flow configuration',
  flowMeta: 'Flow metadata',
  flowDescription: 'Flow description',
  requests: 'Requests',
  postData: 'Post Data',
  mimeType: 'Mime Type',
  text: 'Text',
  extractions: 'Extractions',
  extraction: 'Extraction',
  postScript: 'Post Script',
  assertions: 'Assertions',
  assertion: 'Assertion',
  existsAssertion: 'Exists Assertion',
  check: 'Check',
  notExistsAssertion: 'Not Exists Assertion',
  falsy: 'Falsy',
  equalsAssertion: 'Equals Assertion',
  equals: 'Equals',
  lesserAssertion: 'Lesser Assertion',
  lesser: 'Lesser',
  loop: 'Loop',
  hooks: 'Hooks',
  beforeAll: 'Before All',
  beforeEach: 'Before Each',
  afterEach: 'After Each',
  afterAll: 'After All',
  dependencies: 'Dependencies',
  dependenciesHooks: 'Dependencies Hooks',
  dependenciesLogin: 'Dependencies Login',
};
